# Generated by Django 5.2.7 on 2025-10-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='email',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='name',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
